function cat = get_rotation_angles_wrt_FMref(cat,FM)

cat.refFM = FM;

neq             = numel(cat.lat);
cat.refFM_rotKag = zeros(neq,1);
cat.refFM_rotAbs = zeros(neq,1);

for ieq = 1:neq

    [rota1,~,~] = kagan([cat.stk(ieq), ...
                         cat.dip(ieq), ...
                         cat.rak(ieq)], ...
                        [FM.stk, ...
                         FM.dip, ...
                         FM.rak]);
                    
    rota2 = fault_plane_rot(cat.stk(ieq), ...
                            cat.dip(ieq), ...
                            cat.rak(ieq), ...
                            FM.stk, ...
                            FM.dip, ...
                            FM.rak);
    
    cat.refFM_rotKag(ieq) = rota1;
    cat.refFM_rotAbs(ieq) = rota2;
end