function plot_eigenvectors(evd, n0, e0, d0, c)

if nargin<5; c=1;
end

% Plotting parameters
lnw    = 2;

% Eigenvalues
eval1 = evd.EV(1);
eval2 = evd.EV(2);
eval3 = evd.EV(3);

% Scale eigenvectors by sqauare root of their eigenvalue and factor <c>
v1 = c*sqrt(eval1)*evd.V(:,1);
v2 = c*sqrt(eval2)*evd.V(:,2);
v3 = c*sqrt(eval3)*evd.V(:,3);

dx_txt = norm(v1)/10;

% 1st eigenvector
quiver3(n0, e0, d0, ...
    v1(1), v1(2), v1(3), ...
    'lineWidth', lnw, ...
    'color','r', ...
    'autoscale', 'off')

text(n0 +v1(1) +dx_txt, ...
     e0 +v1(2) +dx_txt, ...
     d0 +v1(3) +dx_txt, ...
     'EV_1', ...
     'color','r')

 
% 2nd eigenvector
quiver3(n0, e0, d0, ...
    v2(1), v2(2), v2(3), ...
    'lineWidth', lnw, ...
    'color','b', ...
    'autoscale', 'off')

text(n0 +v2(1) +dx_txt, ...
     e0 +v2(2) +dx_txt, ...
     d0 +v2(3) +dx_txt, ...
     'EV_2', ...
     'color','b')

 
 % 3rd eigenvector
quiver3(n0, e0, d0, ...
    v3(1), v3(2), v3(3), ...
    'lineWidth', lnw, ...
    'color','c', ...
    'autoscale', 'off')

text(n0 +v3(1) +dx_txt, ...
     e0 +v3(2) +dx_txt, ...
     d0 +v3(3) +dx_txt, ...
     'EV_3', ...
     'color','c')

 