function [hf, fm, finsrc] = plot_3D_beachball_and_finite_source(...
    stk, dip, rak, ...
    x0, y0, z0, ...
    mag, ...
    stressdrop, ...
    view_angle)

if nargin<9; view_angle = [-100 75];
end


% Compute FM vectors
fm = get_all_FM_vectors(stk,dip,rak);


% Compute rectangular finite source patch
finsrc = get_rectangular_slippatch_from_FM(x0, y0, z0, ...
    stk, ...
    dip, ...
    mag, ...
    stressdrop);




%% Plot 3D beachball and finite source 

% Prepare plot
hf     = figure(201); clf; whitebg([.5 .5 .5])
lim    = get_cubic_domain_XYZ(x0, y0, z0, 1.5*finsrc.length);
colour = [1 0 1];

hs1 = subplot(1,2,1); hold on; grid on; box on; axis equal
hs2 = subplot(1,2,2); hold on; grid on; box on; axis equal
tmp = get(hs2); xlabel('x'); ylabel('y'); zlabel('z');
tstring = sprintf('FM: strike=%i°, dip=%i°, rake=%i°', stk, dip, rak);
sgtitle(tstring) 

% 3D beachball
subplot(hs1);
plot_3D_beachball(finsrc.length/2, ...
    [x0 y0 z0], ...
    fm.n1, ...
    fm.n2, ...
    fm.p1', ...
    colour)
xlabel('x'); ylabel('y'); zlabel('z')
%get(hs1); 

% Rectangular finite source
subplot(hs2);
plot_rectangular_slippatch(finsrc, x0, y0, z0, colour)

% Add FM vectors
plot_FM_vectors(fm, x0, y0, z0)

% Link and order both subplots 
Link = linkprop([hs1, hs2],{'CameraUpVector', ...
    'CameraPosition', ...
    'CameraTarget', ...
    'XLim', ...
    'YLim', ...
    'ZLim', ...
    'xDir', ...
    'yDir', ...
    'zDir'});

setappdata(gcf, 'StoreTheLink', Link);

%tmp = get(hs1);
set(hs1,'yDir','reverse', 'zDir','reverse', ...
        'view', view_angle, ...
        'xlim', lim.x, 'ylim', lim.y, 'zlim', lim.z)


    
%% Add the second plane to finsource
finsrc2 = get_rectangular_slippatch_from_FM(x0, y0, z0, ...
        fm.stk2, ...
        fm.dip2, ...
        mag, ...
        stressdrop);
    
subplot(hs2)
fill3( finsrc2.x5(:), finsrc2.y5(:), finsrc2.z5(:), ...
        ones(5,1), ...
        'faceColor', [.7 .7 .7], ...
        'edgeColor', 'k', ...
        'faceAlpha', .3)