function plot_FM_vectors(fm, x0, y0, z0)

c = 10;
dx = c/10;

lnw = 3;

% Slip vector
quiver3(x0, y0, z0, ...
    c*fm.s1(1), c*fm.s1(2), c*fm.s1(3), ...
    'lineWidth', lnw, ...
    'color','k', ...
    'autoscale', 'off')

text(x0 +c*fm.s1(1) +dx, ...
     y0 +c*fm.s1(2) +dx, ...
     z0 +c*fm.s1(3), ...
     's', ...
     'color','k')

% Normal vector    
quiver3(x0, y0, z0, ...
    c*fm.n1(1), c*fm.n1(2), c*fm.n1(3), ...
    'lineWidth', lnw, ...
    'color','r', ...
    'autoscale', 'off')

text(x0 +c*fm.n1(1) +dx, ...
     y0 +c*fm.n1(2) +dx, ...
     z0 +c*fm.n1(3), ...
     'n', ...
     'color','r')
 

% B-vector    
quiver3(x0, y0, z0, ...
    c*fm.b1(1), c*fm.b1(2), c*fm.b1(3), ...
    'lineWidth', lnw, ...
    'color','b', ...
    'autoscale', 'off')

text(x0 +c*fm.b1(1) +dx, ...
     y0 +c*fm.b1(2) +dx, ...
     z0 +c*fm.b1(3), ...
     'b', ...
     'color','b')

 
% P-vector    
% (points towards focal origin)
quiver3(x0 +c/2*fm.p1(1), y0 +c/2*fm.p1(2), z0+c/2*fm.p1(3), ...
    -c/2*fm.p1(1), -c/2*fm.p1(2), -c/2*fm.p1(3), ...
    'lineWidth', lnw, ...
    'color','m', ...
    'autoscale', 'off')

text(x0 +c/2*fm.p1(1) +dx, ...
     y0 +c/2*fm.p1(2) +dx, ...
     z0 +c/2*fm.p1(3), ...
     'P', ...
     'color','m')

% T-vector    
quiver3(x0, y0, z0, ...
    c/2*fm.t1(1), c/2*fm.t1(2), c/2*fm.t1(3), ...
    'lineWidth', lnw, ...
    'color','c', ...
    'autoscale', 'off')

text(x0 +c/2*fm.t1(1) +dx, ...
     y0 +c/2*fm.t1(2) +dx, ...
     z0 +c/2*fm.t1(3), ...
     'T', ...
     'color','c')