function plot_rectangular_slippatch(finsrc, colour)

if nargin<5; colour = [0 0 1];
end

       
plot3(...
    finsrc.n0, ...
    finsrc.e0, ...
    finsrc.d0, ...
    'ok', ...
    'markerFaceColor', 'r')

fill3( ...
    finsrc.n5(:), ...
    finsrc.e5(:), ...
    finsrc.d5(:), ...
    ones(5,1), ...
    'faceColor', colour, ...
    'edgeColor', [.2 .2 .2], ...
    'faceAlpha', .3)

% lim = get_cubic_domain_XYZ(n0, e0, d0, 1.3*finsrc.length);
% set(gca,'xlim', lim.x, ...
%         'ylim', lim.y, ...
%         'zlim', lim.z)